name: devstack-lint
services:
  localstack:
    environment:
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: "0"
      PERSISTENCE: "1"
      SERVICES: s3,sqs,sns,kinesis,dynamodb
    healthcheck:
      test:
        - CMD-SHELL
        - curl -sf http://localhost:4566/_localstack/health | grep -Eq 'available|running'
      timeout: 5s
      interval: 10s
      retries: 8
      start_period: 20s
    image: localstack/localstack:3
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: localstackdata
        target: /var/lib/localstack
        volume: {}
networks:
  default:
    name: devstack-lint_default
volumes:
  localstackdata:
    name: devstack-lint_localstackdata
