package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/open-source-cloud/devstack/internal/config"
	"github.com/open-source-cloud/devstack/internal/prompt"
	"github.com/open-source-cloud/devstack/internal/scaffold"
	"github.com/open-source-cloud/devstack/internal/store"
	"github.com/open-source-cloud/devstack/internal/xdg"
)

// initHeader is the provenance comment prepended to a generated workspace.yaml.
const initHeader = "# Generated by `devstack init` — edit freely; re-run is safe with --force.\n"

// newInitCmd wires `devstack init` — the workspace authoring front door (spec 22).
// It picks shared engines (filtered to those declaring `provides:`), fills their
// typed params, and writes a structurally-validated workspace.yaml. Pure config
// authorship: no ledger, no Docker, no lock. The flag path is the scriptable face;
// the Bubble Tea wizard (the interactive face) feeds the same scaffold builder.
func newInitCmd(g *GlobalOpts) *cobra.Command {
	var (
		name      string
		profile   string
		services  []string
		params    []string
		aliases   []string
		projects  []string
		fromStore bool
		outDir    string
		dryRun    bool
		force     bool
		noInput   bool
	)
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Author a workspace.yaml (pick shared services + params)",
		Long: "init scaffolds a workspace.yaml: pick the shared engines (postgres/redis/minio),\n" +
			"fill their typed params, and write a structurally-validated file. It takes no lock,\n" +
			"starts no Docker, and never recreates a stateful service — it just authors config.\n" +
			"Run with flags for a scriptable result; run it bare in a terminal for the wizard.",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if outDir == "" {
				outDir = "."
			}
			absOut, err := filepath.Abs(outDir)
			if err != nil {
				return err
			}
			if err := xdg.RefuseWindowsMount(absOut); err != nil {
				return err
			}
			// Refuse to nest inside an existing workspace (a parent dir owns one).
			// A workspace.yaml in the target dir itself is handled by the no-clobber
			// check below, so only a strictly-higher root is a hard error here.
			if root, derr := config.Discover(absOut); derr == nil && root != absOut {
				return fmt.Errorf("already inside a workspace at %s (nested workspaces are unsupported)", root)
			}

			// Two faces, one builder: a bare invocation on a TTY runs the wizard;
			// any input flag, --no-input, --json/--quiet, non-TTY, or CI takes the
			// scriptable flag path. Both produce a scaffold.Inputs.
			hasFlags := len(services) > 0 || len(projects) > 0 || len(aliases) > 0 ||
				len(params) > 0 || name != "" || fromStore
			var in scaffold.Inputs
			if prompt.IsInteractive(g.JSON, g.Quiet, noInput) && !hasFlags {
				seed := map[string]config.SharedSvc{}
				if cfg, ok, _ := store.Load(); ok {
					seed = cfg.Shared
				}
				in, err = runInitWizard(builtinSource(), seed, scaffold.SanitizeName(filepath.Base(absOut)))
				if errors.Is(err, errInitCancelled) {
					if !g.Quiet {
						fmt.Fprintln(cmd.ErrOrStderr(), "init cancelled — nothing written")
					}
					return nil
				}
				if err != nil {
					return err
				}
			} else {
				in, err = inputsFromFlags(flagInputs{
					name: name, profile: profile, services: services, params: params,
					aliases: aliases, projects: projects, fromStore: fromStore, absOut: absOut,
				})
				if err != nil {
					return err
				}
			}

			ws, err := scaffold.BuildWorkspace(builtinSource(), in)
			if err != nil {
				return err
			}
			body, err := scaffold.EmitWorkspaceYAML(ws)
			if err != nil {
				return err
			}
			out := append([]byte(initHeader), body...)
			if err := config.ValidateWorkspaceBytes(out); err != nil {
				return err
			}

			target := filepath.Join(outDir, config.WorkspaceFile)
			if dryRun {
				if g.JSON {
					return writeJSON(cmd, initSummaryOf(ws, target, false))
				}
				w := cmd.OutOrStdout()
				fmt.Fprintf(w, "%s\n--- %s ---\n(dry-run: validates ok, nothing written)\n", out, target)
				return nil
			}

			if err := writeWorkspaceFile(target, out, force); err != nil {
				return err
			}

			if g.JSON {
				return writeJSON(cmd, initSummaryOf(ws, target, true))
			}
			if !g.Quiet {
				w := cmd.OutOrStdout()
				fmt.Fprintf(w, "wrote %s\n", target)
				fmt.Fprintf(w, "next: run `%s up` to start the shared stack\n", rootName(cmd))
			}
			return nil
		},
	}
	f := cmd.Flags()
	f.StringVar(&name, "name", "", "workspace name (default: sanitized basename of --out)")
	f.StringVar(&profile, "profile", "dev", "default env profile")
	f.StringArrayVar(&services, "service", nil, "shared engine to add, repeatable (e.g. postgres@16, redis, minio)")
	f.StringArrayVar(&params, "param", nil, "override a shared-service param, repeatable (svc.key=value)")
	f.StringArrayVar(&aliases, "alias", nil, "workspace alias, repeatable")
	f.StringArrayVar(&projects, "project", nil, "project ref, repeatable (name=path[,git=url])")
	f.BoolVar(&fromStore, "from-store", false, "seed shared services from the global store (~/.devstack/config.yaml)")
	f.StringVar(&outDir, "out", "", "output directory (default: current directory)")
	f.BoolVar(&dryRun, "dry-run", false, "print the would-be file + validation verdict, write nothing")
	f.BoolVar(&force, "force", false, "overwrite an existing workspace.yaml (backs up the original first)")
	f.BoolVar(&noInput, "no-input", false, "never launch the wizard; use flags only (implied by --json/--quiet/non-TTY/CI)")
	return cmd
}

// flagInputs carries the raw flag values into the parser.
type flagInputs struct {
	name, profile             string
	services, params, aliases []string
	projects                  []string
	fromStore                 bool
	absOut                    string
}

// inputsFromFlags parses the flag surface into a scaffold.Inputs (the same struct
// the wizard produces). Engine/param/project syntax is validated here; semantic
// validation (unknown engine, missing required param) happens in BuildWorkspace.
func inputsFromFlags(f flagInputs) (scaffold.Inputs, error) {
	name := f.name
	if name == "" {
		name = scaffold.SanitizeName(filepath.Base(f.absOut))
	}

	svcByName := map[string]*scaffold.ServiceInput{}
	var order []string
	for _, raw := range f.services {
		engine, ver, hasVer := strings.Cut(raw, "@")
		if engine == "" {
			return scaffold.Inputs{}, fmt.Errorf("--service %q: empty engine name", raw)
		}
		si, ok := svcByName[engine]
		if !ok {
			si = &scaffold.ServiceInput{Engine: engine, Params: map[string]string{}}
			svcByName[engine] = si
			order = append(order, engine)
		}
		if hasVer {
			if ver == "" {
				return scaffold.Inputs{}, fmt.Errorf("--service %q: empty version after '@'", raw)
			}
			si.Params["version"] = ver
		}
	}
	for _, raw := range f.params {
		lhs, val, ok := strings.Cut(raw, "=")
		if !ok {
			return scaffold.Inputs{}, fmt.Errorf("--param %q: expected svc.key=value", raw)
		}
		svc, key, ok := strings.Cut(lhs, ".")
		if !ok || svc == "" || key == "" {
			return scaffold.Inputs{}, fmt.Errorf("--param %q: expected svc.key=value", raw)
		}
		si, ok := svcByName[svc]
		if !ok {
			return scaffold.Inputs{}, fmt.Errorf("--param %q: unknown service %q (add --service %s first)", raw, svc, svc)
		}
		si.Params[key] = val
	}
	svcInputs := make([]scaffold.ServiceInput, 0, len(order))
	for _, engine := range order {
		svcInputs = append(svcInputs, *svcByName[engine])
	}

	projRefs, err := parseProjects(f.projects)
	if err != nil {
		return scaffold.Inputs{}, err
	}

	var fromStore map[string]config.SharedSvc
	if f.fromStore {
		cfg, ok, err := store.Load()
		if err != nil {
			return scaffold.Inputs{}, err
		}
		if ok {
			fromStore = cfg.Shared
		}
	}

	return scaffold.Inputs{
		Name: name, Profile: f.profile, Aliases: f.aliases,
		Services: svcInputs, Projects: projRefs, FromStore: fromStore,
	}, nil
}

// parseProjects parses `name=path[,git=url]` entries into ProjectRefs.
func parseProjects(raw []string) ([]config.ProjectRef, error) {
	var refs []config.ProjectRef
	for _, r := range raw {
		pname, rest, ok := strings.Cut(r, "=")
		if !ok || pname == "" {
			return nil, fmt.Errorf("--project %q: expected name=path[,git=url]", r)
		}
		parts := strings.Split(rest, ",")
		ref := config.ProjectRef{Name: pname, Path: parts[0]}
		for _, extra := range parts[1:] {
			git, found := strings.CutPrefix(extra, "git=")
			if !found {
				return nil, fmt.Errorf("--project %q: unknown segment %q (only git= is supported)", r, extra)
			}
			ref.Git = git
		}
		if ref.Path == "" {
			ref.Path = pname
		}
		refs = append(refs, ref)
	}
	return refs, nil
}

// writeWorkspaceFile writes target atomically (temp + rename, 0644), refusing to
// clobber an existing file unless force (which backs up the original first).
func writeWorkspaceFile(target string, body []byte, force bool) error {
	if _, err := os.Stat(target); err == nil {
		if !force {
			return fmt.Errorf("%s already exists; pass --force to overwrite (the original is backed up)", target)
		}
		if err := os.Rename(target, fmt.Sprintf("%s.bak.%d", target, time.Now().Unix())); err != nil {
			return fmt.Errorf("back up %s: %w", target, err)
		}
	}
	dir := filepath.Dir(target)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, ".workspace-*.yaml.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if _, err := tmp.Write(body); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmpName, 0o644); err != nil {
		return err
	}
	return os.Rename(tmpName, target)
}

type initSummary struct {
	Workspace string   `json:"workspace"`
	Shared    []string `json:"shared"`
	Projects  []string `json:"projects"`
	Wrote     bool     `json:"wrote"`
}

func initSummaryOf(ws config.Workspace, target string, wrote bool) initSummary {
	shared := make([]string, 0, len(ws.Shared))
	for n := range ws.Shared {
		shared = append(shared, n)
	}
	sort.Strings(shared)
	projects := make([]string, 0, len(ws.Projects))
	for _, p := range ws.Projects {
		projects = append(projects, p.Name)
	}
	sort.Strings(projects)
	return initSummary{Workspace: target, Shared: shared, Projects: projects, Wrote: wrote}
}
