// Package migrate converts a legacy devdock single-file project.yaml into the
// clean-slate two-file devstack schema: a workspace.yaml (shared layer) plus a
// per-repo devstack.yaml (portable project layer) — spec 14 §import. It is a
// converter PLUS a guide, not byte-compatible: the mapping is intentional
// (devdock global services → workspace shared; devdock per-service
// template/params/env/uses → each repo's devstack.yaml; devdock `${svc.var}` →
// the typed `${ref:workspace.shared.svc.var}` grammar; `!Repo`/repo shorthand →
// the internal/git shorthand superset).
//
// It is LOSSLESS-OR-LOUD (spec 14): parsing is tolerant — every field it cannot
// confidently convert is recorded in a conversion report (path, value, reason)
// rather than dropped silently — so an unknown devdock dialect degrades to a
// reviewable report instead of a wrong-but-plausible config.
package migrate

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/goccy/go-yaml"

	"github.com/open-source-cloud/devstack/internal/git"
)

// APIVersion stamped on every emitted file.
const APIVersion = "devstack/v1"

// knownEngines maps a devdock template/image keyword to a devstack shared engine.
var knownEngines = map[string]string{
	"postgres": "postgres", "postgresql": "postgres", "postgis": "postgres",
	"redis": "redis", "valkey": "redis",
	"minio": "minio",
}

// ReportEntry is one unconvertible (or noteworthy) field.
type ReportEntry struct {
	Path   string
	Value  string
	Reason string
}

// Result is the converted output: the workspace file, each project's file, and
// the conversion report.
type Result struct {
	WorkspaceYAML []byte
	Projects      map[string][]byte // project name -> devstack.yaml bytes
	Report        []ReportEntry
}

var interpRe = regexp.MustCompile(`\$\{([A-Za-z0-9_-]+)\.([A-Za-z0-9_.-]+)\}`)

// Convert parses a devdock project.yaml and returns the two-file split + report.
// workspaceName defaults the workspace name when the source declares none.
func Convert(src []byte, workspaceName string) (*Result, error) {
	var doc map[string]any
	if err := yaml.Unmarshal(src, &doc); err != nil {
		return nil, fmt.Errorf("parse devdock project.yaml: %w", err)
	}
	res := &Result{Projects: map[string][]byte{}}

	name := workspaceName
	if n := getStr(doc, "name", "project", "workspace"); n != "" {
		name = n
	}
	if name == "" {
		name = "imported"
	}

	services := getMap(doc["services"])
	if services == nil {
		// Tolerant fallback: some dialects put services at the top level.
		services = topLevelServices(doc)
		if services == nil {
			res.note("services", "", "no `services` map found; nothing to convert")
		}
	}

	// Pass 1: classify every service so uses/env rewrites know the shared set.
	type svc struct {
		def    map[string]any
		engine string // "" if not a known engine
		repo   string // "" if not a project service
	}
	svcs := map[string]svc{}
	sharedSet := map[string]bool{}
	for _, sname := range sortedKeys(services) {
		def := getMap(services[sname])
		if def == nil {
			res.note("services."+sname, fmt.Sprintf("%v", services[sname]), "service is not a mapping; skipped")
			continue
		}
		repo := getStr(def, "repo", "git", "Repo")
		engine := classifyEngine(getStr(def, "template"), getStr(def, "image"))
		svcs[sname] = svc{def: def, engine: engine, repo: repo}
		if repo == "" && engine != "" {
			sharedSet[sname] = true
		}
	}

	// Pass 2: build the workspace shared map + per-project files.
	shared := yaml.MapSlice{}
	var projectRefs []yaml.MapSlice
	for _, sname := range sortedKeys(services) {
		s, ok := svcs[sname]
		if !ok {
			continue
		}
		switch {
		case s.repo != "":
			projectRefs = append(projectRefs, projectRef(sname, s.repo))
			res.Projects[sname] = res.buildProjectFile(sname, s.def, sharedSet)
		case s.engine != "":
			shared = append(shared, yaml.MapItem{Key: sname, Value: buildSharedEntry(s.engine, s.def)})
		default:
			// No repo and not a known engine: can't place it confidently. Emit it as
			// a standalone project (no git) and flag it for the user to resolve.
			res.note("services."+sname, getStr(s.def, "template", "image"),
				"no repo and not a recognized engine — emitted as a git-less project; set its `git:` or move it under `shared:`")
			projectRefs = append(projectRefs, projectRef(sname, ""))
			res.Projects[sname] = res.buildProjectFile(sname, s.def, sharedSet)
		}
	}

	ws := yaml.MapSlice{
		{Key: "apiVersion", Value: APIVersion},
		{Key: "kind", Value: "Workspace"},
		{Key: "name", Value: name},
	}
	if len(shared) > 0 {
		ws = append(ws, yaml.MapItem{Key: "shared", Value: shared})
	}
	ws = append(ws, yaml.MapItem{Key: "projects", Value: projectRefs})

	out, err := yaml.Marshal(ws)
	if err != nil {
		return nil, err
	}
	res.WorkspaceYAML = append([]byte("# Generated by `devstack import` — review before committing. See docs/MIGRATION.md\n"), out...)
	return res, nil
}

// buildSharedEntry renders one workspace `shared:` value.
func buildSharedEntry(engine string, def map[string]any) yaml.MapSlice {
	entry := yaml.MapSlice{{Key: "template", Value: engine}}
	if params := getMap(def["params"]); len(params) > 0 {
		entry = append(entry, yaml.MapItem{Key: "params", Value: orderedMap(params)})
	}
	return entry
}

// buildProjectFile renders one project's devstack.yaml.
func (r *Result) buildProjectFile(project string, def map[string]any, sharedSet map[string]bool) []byte {
	svc := yaml.MapSlice{}
	if t := getStr(def, "template"); t != "" {
		svc = append(svc, yaml.MapItem{Key: "template", Value: t})
	} else if img := getStr(def, "image"); img != "" {
		r.note("services."+project+".image", img, "devdock image had no template; left as a `image:` note — pick a devstack template")
		svc = append(svc, yaml.MapItem{Key: "image", Value: img})
	}
	if params := getMap(def["params"]); len(params) > 0 {
		svc = append(svc, yaml.MapItem{Key: "params", Value: orderedMap(params)})
	}
	if uses := r.mapUses(project, def, sharedSet); len(uses) > 0 {
		svc = append(svc, yaml.MapItem{Key: "uses", Value: uses})
	}
	if env := r.mapEnv(project, def, sharedSet); len(env) > 0 {
		svc = append(svc, yaml.MapItem{Key: "env", Value: env})
	}

	doc := yaml.MapSlice{
		{Key: "apiVersion", Value: APIVersion},
		{Key: "kind", Value: "Project"},
		{Key: "name", Value: project},
		{Key: "services", Value: yaml.MapSlice{{Key: project, Value: svc}}},
	}
	out, err := yaml.Marshal(doc)
	if err != nil {
		return []byte("# conversion error: " + err.Error() + "\n")
	}
	return append([]byte("# Generated by `devstack import` — review before committing. See docs/MIGRATION.md\n"), out...)
}

// mapUses rewrites devdock `uses`/`depends_on` to workspace.shared.<name> refs.
func (r *Result) mapUses(project string, def map[string]any, sharedSet map[string]bool) []any {
	raw := getList(def["uses"])
	if raw == nil {
		raw = getList(def["depends_on"])
	}
	var out []any
	for _, u := range raw {
		if sharedSet[u] {
			out = append(out, "workspace.shared."+u)
		} else {
			r.note("services."+project+".uses", u, "target is not a recognized shared service; left as-is — point it at a workspace.shared.<name> or workspace.<project>.<service>")
			out = append(out, u)
		}
	}
	return out
}

// mapEnv rewrites devdock `${svc.var}` interpolation to the typed
// `${ref:workspace.shared.svc.var}` grammar for known shared services.
func (r *Result) mapEnv(project string, def map[string]any, sharedSet map[string]bool) yaml.MapSlice {
	env := getMap(def["env"])
	if env == nil {
		env = getMap(def["environment"])
	}
	if len(env) == 0 {
		return nil
	}
	out := yaml.MapSlice{}
	for _, k := range sortedKeys(env) {
		val := fmt.Sprintf("%v", env[k])
		val = interpRe.ReplaceAllStringFunc(val, func(m string) string {
			sub := interpRe.FindStringSubmatch(m)
			svc, attr := sub[1], sub[2]
			if sharedSet[svc] {
				return "${ref:workspace.shared." + svc + "." + attr + "}"
			}
			r.note("services."+project+".env."+k, m, "interpolation references a non-shared service; left as-is — express it with ${ref:workspace.<project>.<service>.<attr>}")
			return m
		})
		out = append(out, yaml.MapItem{Key: k, Value: val})
	}
	return out
}

func (r *Result) note(path, value, reason string) {
	r.Report = append(r.Report, ReportEntry{Path: path, Value: value, Reason: reason})
}

// projectRef builds a workspace `projects:` entry; git is the expanded shorthand.
func projectRef(name, repo string) yaml.MapSlice {
	ref := yaml.MapSlice{{Key: "name", Value: name}, {Key: "path", Value: name}}
	if repo != "" {
		ref = append(ref, yaml.MapItem{Key: "git", Value: git.ExpandURL(repo)})
	}
	return ref
}

// classifyEngine returns the devstack shared engine for a devdock template/image,
// or "" if it is not a recognized stateful engine.
func classifyEngine(template, image string) string {
	for _, hint := range []string{template, image} {
		h := strings.ToLower(hint)
		for kw, engine := range knownEngines {
			if strings.Contains(h, kw) {
				return engine
			}
		}
	}
	return ""
}

// --- tolerant accessors -----------------------------------------------------

func getMap(v any) map[string]any {
	if m, ok := v.(map[string]any); ok {
		return m
	}
	return nil
}

func getStr(m map[string]any, keys ...string) string {
	for _, k := range keys {
		if v, ok := m[k]; ok {
			if s, ok := v.(string); ok {
				return s
			}
		}
	}
	return ""
}

func getList(v any) []string {
	s, ok := v.([]any)
	if !ok {
		return nil
	}
	var out []string
	for _, e := range s {
		if str, ok := e.(string); ok {
			out = append(out, str)
		}
	}
	return out
}

// topLevelServices treats the doc's mapping-valued top-level keys as services
// (a tolerant fallback when there is no explicit `services:` block).
func topLevelServices(doc map[string]any) map[string]any {
	out := map[string]any{}
	for k, v := range doc {
		switch k {
		case "name", "project", "workspace", "version", "apiVersion":
			continue
		}
		if getMap(v) != nil {
			out[k] = v
		}
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

func orderedMap(m map[string]any) yaml.MapSlice {
	out := yaml.MapSlice{}
	for _, k := range sortedKeys(m) {
		out = append(out, yaml.MapItem{Key: k, Value: m[k]})
	}
	return out
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// RenderReport formats the conversion report for printing / writing next to the
// output (spec 14 §lossless-or-loud).
func RenderReport(entries []ReportEntry) string {
	if len(entries) == 0 {
		return "conversion report: clean — every field converted.\n"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "conversion report: %d field(s) need your attention\n", len(entries))
	for _, e := range entries {
		fmt.Fprintf(&b, "  - %s", e.Path)
		if e.Value != "" {
			fmt.Fprintf(&b, " (%q)", e.Value)
		}
		fmt.Fprintf(&b, ": %s\n", e.Reason)
	}
	return b.String()
}
