package ai

import (
	"bytes"
	"fmt"
)

// claudeImportBlock is what goes inside CLAUDE.md's fence. Claude Code reads
// CLAUDE.md and does not read AGENTS.md, so the import line is what makes the one
// authored block serve both. Everything else in the user's CLAUDE.md is untouched.
const claudeImportBlock = `@AGENTS.md

The devstack section of AGENTS.md above is generated by ` + "`%s ai install`" + `.
Run ` + "`%s ai docs`" + ` to read devstack's full documentation from the binary.`

// buildAgentsMD renders the AGENTS.md block and the CLAUDE.md import.
//
// AGENTS.md is the portable surface: Codex, Cursor, Copilot, Gemini CLI,
// Windsurf, Zed and Aider read it natively and read none of .claude/skills/. It
// therefore has to stand alone rather than defer to the skills.
//
// Both files use MergeFence, so they are created if absent and otherwise have
// only devstack's block replaced — a user's own instructions survive every
// regeneration. Emitting five near-duplicate per-tool rule files
// (.cursorrules, .github/copilot-instructions.md, GEMINI.md, …) is deliberately
// NOT done: AGENTS.md is the cross-tool standard, and five copies is precisely
// the drift this design exists to avoid.
func (g *Generator) buildAgentsMD() ([]Artifact, error) {
	body, err := packBody(PackAgents)
	if err != nil {
		return nil, err
	}
	arts := []Artifact{
		g.artifact("agents-md", MergeFence, g.rewriteBinary(body), "AGENTS.md"),
	}

	var claude bytes.Buffer
	fmt.Fprintf(&claude, claudeImportBlock, g.binary, g.binary)
	arts = append(arts, g.artifact("claude-md", MergeFence, claude.Bytes(), "CLAUDE.md"))
	return arts, nil
}
