name: devstack-lint
services:
  nats:
    command:
      - -js
      - -sd
      - /data
      - -m
      - "8222"
    healthcheck:
      test:
        - CMD-SHELL
        - wget -qO- http://localhost:8222/healthz || exit 1
      timeout: 5s
      interval: 10s
      retries: 5
    image: nats:2
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: natsdata
        target: /data
        volume: {}
networks:
  default:
    name: devstack-lint_default
volumes:
  natsdata:
    name: devstack-lint_natsdata
