name: devstack-lint
services:
  kafka:
    command:
      - redpanda
      - start
      - --mode=dev-container
      - --smp=1
      - --default-log-level=warn
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://shared-kafka:9092,external://127.0.0.1:49092
    healthcheck:
      test:
        - CMD-SHELL
        - rpk cluster health -x admin.hosts=localhost:9644 | grep -q 'Healthy:.*true'
      timeout: 5s
      interval: 10s
      retries: 8
      start_period: 15s
    image: redpandadata/redpanda:v24.2
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: kafkadata
        target: /var/lib/redpanda/data
        volume: {}
networks:
  default:
    name: devstack-lint_default
volumes:
  kafkadata:
    name: devstack-lint_kafkadata
